"""Validate the chemistry wrapper against PHREEQC reference values.

The expected numbers are not ours and are not reaktoro's: they ship with
reaktoro-pse as `phreeqc_data.json`, generated by PHREEQC itself for the
water-removal comparison. Checking against them catches the failure this wrapper
is most exposed to — an activity model or a state assumption that yields
confident, plausible, wrong numbers.

Reaktoro and PHREEQC are different codes, so exact agreement is not the bar.
Upstream's own comparison figures show a few percent spread; the tolerances here
are set to catch a *modelling* error, not numerical noise.

Run: /home/bayan/reaktoro-mcp/env/bin/python mcp_watertap/test_reaktoro_model.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from reaktoro_model import (
    ReaktoroSimulationError,
    composition_salinity,
    equilibrate,
)

# Conditions from reaktoro-pse's standard_model.build_modification_example.
REFERENCE_TEMPERATURE_C = 20.0
REFERENCE_PRESSURE_BAR = 10.0
REFERENCE_PH = 7.8
REFERENCE_PE = 4.0
REFERENCE_MINERALS = ["Calcite", "Gypsum", "Anhydrite"]

# Relative tolerances, except pH. Scaling tendencies span orders of magnitude, so
# they get the loosest band.
TOL_SCALING = 0.15
TOL_OSMOTIC = 0.10

# pH is already logarithmic, so a *relative* tolerance on it is meaningless — it
# would grade a 0.03-unit difference against the arbitrary magnitude of the
# number. Bounded in pH units instead. 0.05 is far below any operationally
# meaningful difference and still an order of magnitude tighter than the scaling
# bands, which is where a wrong activity model would show up first.
TOL_PH_UNITS = 0.05


def _load_reference() -> dict | None:
    """Locate phreeqc_data.json inside the installed reaktoro-pse package."""
    try:
        import reaktoro_pse
    except ImportError:
        return None
    path = (
        Path(reaktoro_pse.__file__).parent
        / "examples"
        / "reaktoro_pse_to_phreeqc_comparison"
        / "phreeqc_data.json"
    )
    if not path.is_file():
        return None
    return json.loads(path.read_text())


def check(label: str, got: float, expected: float, rtol: float) -> bool:
    ok = abs(got - expected) <= rtol * abs(expected)
    delta = (got - expected) / expected * 100 if expected else float("nan")
    print(
        f"  {label:28s} {got:>14.6g} {expected:>14.6g} {delta:>+8.2f}%  "
        f"{'ok' if ok else 'MISMATCH'}"
    )
    return ok


def check_abs(label: str, got: float, expected: float, atol: float) -> bool:
    ok = abs(got - expected) <= atol
    print(
        f"  {label:28s} {got:>14.6g} {expected:>14.6g} {got - expected:>+8.3f}   "
        f"{'ok' if ok else 'MISMATCH'}"
    )
    return ok


def test_against_phreeqc(ref: dict) -> int:
    failures = 0
    feed = ref["feed_comp"]
    sweep = ref["water_removal_percent_sweep"]
    percents = ref["water_removal_percent"]

    print("1. Water-removal sweep vs PHREEQC reference")
    for i, pct in enumerate(percents):
        # 0% removal is the unconcentrated feed; the wrapper takes that as
        # water_recovery=None rather than 0.
        recovery = None if pct == 0 else pct / 100.0
        try:
            r = equilibrate(
                composition=feed,
                temperature_c=REFERENCE_TEMPERATURE_C,
                pressure_bar=REFERENCE_PRESSURE_BAR,
                ph=REFERENCE_PH,
                pe=REFERENCE_PE,
                water_recovery=recovery,
                minerals=REFERENCE_MINERALS,
            )
        except ReaktoroSimulationError as exc:
            print(f"  {pct:>5.0f}% removal -> FAILED: {exc}")
            failures += 1
            continue

        print(f"  {pct:>5.0f}% water removed")
        results = [
            check("Calcite ST", r["scaling_tendency"]["Calcite"],
                  sweep["Calcite"][i], TOL_SCALING),
            check("Gypsum ST", r["scaling_tendency"]["Gypsum"],
                  sweep["Gypsum"][i], TOL_SCALING),
            check("Anhydrite ST", r["scaling_tendency"]["Anhydrite"],
                  sweep["Anhydrite"][i], TOL_SCALING),
            check_abs("pH", r["solution"]["ph"], sweep["pH"][i], TOL_PH_UNITS),
            check("osmotic pressure Pa", r["solution"]["osmotic_pressure_Pa"],
                  sweep["Osmotic pressure"][i], TOL_OSMOTIC),
        ]
        if not all(results):
            failures += 1
    return failures


def test_ph_responds(ref: dict) -> int:
    """pH must fall as the solution concentrates.

    Guards the specific bug this file was written after: modelling concentration
    by subtracting water from the composition pins the concentrate to the feed's
    fixed pH, so the reported pH is the input echoed back. That reads as a
    perfectly stable pH and is wrong.
    """
    print("\n2. pH responds to concentration (not echoing the input)")
    feed = ref["feed_comp"]
    phs = []
    for rec in (0.3, 0.6, 0.9):
        r = equilibrate(
            composition=feed,
            temperature_c=REFERENCE_TEMPERATURE_C,
            pressure_bar=REFERENCE_PRESSURE_BAR,
            ph=REFERENCE_PH,
            pe=REFERENCE_PE,
            water_recovery=rec,
        )
        phs.append(r["solution"]["ph"])
    print(f"  30/60/90% removal -> pH {phs[0]:.4f} / {phs[1]:.4f} / {phs[2]:.4f}")
    if any(abs(p - REFERENCE_PH) < 1e-6 for p in phs):
        print(f"  MISMATCH: pH equals the input {REFERENCE_PH} — it is being pinned")
        return 1
    if not (phs[0] > phs[1] > phs[2]):
        print("  MISMATCH: pH should fall monotonically as water is removed")
        return 1
    return 0


def test_acid_selectivity() -> int:
    """Acid suppresses carbonate scale and leaves sulfate scale alone."""
    print("\n3. Acid dosing suppresses Calcite but not Gypsum")
    base = equilibrate(water_recovery=0.75, minerals=["Calcite", "Gypsum"])
    dosed = equilibrate(
        water_recovery=0.75, acid_addition_mol_s=0.002, minerals=["Calcite", "Gypsum"]
    )
    ca_drop = dosed["scaling_tendency"]["Calcite"] / base["scaling_tendency"]["Calcite"]
    gy_ratio = dosed["scaling_tendency"]["Gypsum"] / base["scaling_tendency"]["Gypsum"]
    print(f"  Calcite ST x{ca_drop:.4f} | Gypsum ST x{gy_ratio:.4f}")
    failures = 0
    if ca_drop > 0.1:
        print("  MISMATCH: acid should drop Calcite ST by at least 10x")
        failures += 1
    if not 0.9 < gy_ratio < 1.1:
        print("  MISMATCH: Gypsum ST should be near-unchanged by acid")
        failures += 1
    return failures


def test_salinity() -> int:
    print("\n4. Salinity conversion")
    s = composition_salinity({"H2O": 55.5, "Na": 0.5, "Cl": 0.5})
    expected_g = 0.5 * 22.990 + 0.5 * 35.453
    expected_tds = expected_g / (55.5 * 18.015) * 1000
    ok = check("TDS g/kg water", s["tds_g_per_kg_water"], expected_tds, 1e-9)
    failures = 0 if ok else 1
    try:
        composition_salinity({"H2O": 55.5, "Xx": 1.0})
        print("  unknown species          -> NOT REJECTED")
        failures += 1
    except ReaktoroSimulationError:
        print("  unknown species          -> rejected")
    return failures


def test_rejects_bad_input() -> int:
    print("\n5. Invalid input is rejected, not silently wrong")
    failures = 0
    for kwargs, why in [
        ({"minerals": ["Unobtainium"]}, "unknown mineral"),
        ({"water_recovery": 1.5}, "recovery above 1"),
        ({"composition": {"Na": 1.0}}, "composition without H2O"),
        ({"ph": 20}, "pH out of range"),
        ({"nonexistent_param": 1}, "unknown parameter"),
    ]:
        try:
            equilibrate(**kwargs)
            print(f"  {why:26s} -> NOT REJECTED")
            failures += 1
        except ReaktoroSimulationError:
            print(f"  {why:26s} -> rejected")
    return failures


def main() -> int:
    ref = _load_reference()
    if ref is None:
        print("phreeqc_data.json not found; is reaktoro-pse installed?")
        return 1

    failures = test_against_phreeqc(ref)
    failures += test_ph_responds(ref)
    failures += test_acid_selectivity()
    failures += test_salinity()
    failures += test_rejects_bad_input()

    print("\nFAILURES:", failures)
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
